[project]
name = "telegram-bot"
version = "0.1.0"
requires-python = ">=3.9, <3.12.3"
dependencies = [
    "python-telegram-bot",
    "pydantic"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
